from core.state import CopilotState
from utils.llm_provider import get_llm
from langchain_core.messages import SystemMessage, HumanMessage

def contradictor_node(state: CopilotState) -> CopilotState:
    llm = get_llm()
    if llm is None:
        return {
            "contradictor_notes": None,
            "error": "LLM is not configured.",
        }
    
    final_answer = state.get("analytical_response")
    messages = state.get("messages", [])
    business_rules = state.get("business_rules", "No business rules found.")
    chat_history_text = ""
    for m in messages:
        role = "Utilisateur" if m.type == "human" else "Assistant"
        chat_history_text += f"{role}: {m.content}\n"
    language = state.get("language", "français")

    system_prompt = f"""
    You are the Contradictor/Security Auditor for the Montreal Mobility Copilot.
    Your role is to provide a critical perspective and nuance to the final response generated by the Synthesis Agent.

    🚨 HACKATHON REQUIRED STRUCTURE 🚨
    You MUST format your response exactly with these two sections (adapt the language of the section titles to match the user's language : {language}):
    
    1. 🛑 Limites et risques d'interprétation :
    (Highlight biases: e.g., 311 data is declarative and may not reflect the full reality, weather data is regional, or the sample size might be too small. Use the RAG CONTEXT to check if the official definitions limit the scope of the findings. Emphasize that real-world conditions always take precedence).
    
    2. 🔍 Ce que je vérifierais ensuite :
    (Suggest the next logical step. E.g., cross-referencing with STM data, sending an inspection team, or looking at a longer timeframe).

    INSTRUCTIONS:
    1. Be constructive, analytical, and concise (maximum 2-3 sentences per section).
    2. Speak in a clear manner for a general audience. Avoid technical jargon like 'SQL' or 'database'.
    3. Always reply in the user's language ({language}).
    4. You can add sources if it's relevant.
    5. If a prediction about number of accident is made using the predictive model, always add a note about the limitations of the model.
    """

    prompt_context = f"""
    Business rules: {business_rules}
    Chat history: {chat_history_text}
    SQL results: {state.get("query_results")}
    Final answer: {final_answer}

    Generate the contradictor report based strictly on the above information and the required structure.
    """

    final_message = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=prompt_context)
    ]

    response = llm.invoke(final_message)

    return {
        "contradictor_notes": response.content,
        }