import re
from typing import Dict, Optional
from langchain_core.messages import SystemMessage

from core.state import CopilotState
from utils.llm_provider import get_llm
from core.tools.tools_api_weather_now import geomet_mtl_weather_text_bundle
from core.tools.tools_api_histo import geomet_mtl_history_global_tool

_SQL_BLOCK_PATTERN = re.compile(r"```(?:sql)?\s*(.*?)```", re.IGNORECASE | re.DOTALL)
_XML_TAG_PATTERN = re.compile(r"<\/?(?:sql|query|answer|response)[^>]*>", re.IGNORECASE)
_LINE_COMMENT_PATTERN = re.compile(r"--.*?$", re.MULTILINE)
_BLOCK_COMMENT_PATTERN = re.compile(r"/\*.*?\*/", re.DOTALL)

_FORBIDDEN_SQL_KEYWORDS = {
	"INSERT",
	"UPDATE",
	"DELETE",
	"DROP",
	"ALTER",
	"TRUNCATE",
	"ATTACH",
	"DETACH",
	"PRAGMA",
	"VACUUM",
	"CREATE",
	"REPLACE",
	"GRANT",
	"REVOKE",
	"COMMIT",
	"ROLLBACK",
	"BEGIN",
	"END",
	"EXEC",
	"EXECUTE",
	"CALL",
}

def _strip_llm_wrappers(raw_text: str) -> str:
	text = (raw_text or "").strip()
	if not text:
		return ""

	fenced_match = _SQL_BLOCK_PATTERN.search(text)
	if fenced_match:
		text = fenced_match.group(1).strip()

	text = _XML_TAG_PATTERN.sub("", text)
	text = text.strip()

	if text.lower().startswith("sql:"):
		text = text[4:].strip()

	return text


def _normalize_sql(sql: str) -> str:
	sql = _BLOCK_COMMENT_PATTERN.sub(" ", sql)
	sql = _LINE_COMMENT_PATTERN.sub(" ", sql)
	sql = re.sub(r"\s+", " ", sql).strip()
	if sql.endswith(";"):
		sql = sql[:-1].strip()
	return sql


def _sanitize_sql_query(candidate: str) -> str:
	if not candidate:
		raise ValueError("Empty SQL query generated by LLM.")

	sql = _normalize_sql(candidate)
	if not sql:
		raise ValueError("SQL query is empty after normalization.")

	if ";" in sql:
		raise ValueError("Only one SQL statement is allowed.")

	upper_sql = sql.upper()
	if not (upper_sql.startswith("SELECT ") or upper_sql.startswith("WITH ")):
		raise ValueError("Only read-only SQL queries (SELECT/WITH) are allowed.")

	for keyword in _FORBIDDEN_SQL_KEYWORDS:
		if re.search(rf"\b{re.escape(keyword)}\b", upper_sql):
			raise ValueError(f"Forbidden SQL keyword detected: {keyword}")

	return sql


def sql_generator_node(state: CopilotState) -> CopilotState:
	messages = state.get("messages", [])
	if not any(getattr(message, "type", None) == "human" for message in messages):
		return {
			"generated_query": None,
			"query_error": "No user question found in messages.",
		}

	llm = get_llm()
	if llm is None:
		return {
			"generated_query": None,
			"query_error": "LLM is not configured.",
		}
	if not hasattr(llm, "bind_tools"):
		return {
			"generated_query": None,
			"query_error": "Configured LLM does not support tool binding (bind_tools).",
		}

	tools = [geomet_mtl_weather_text_bundle,geomet_mtl_history_global_tool]
	llm_with_tools = llm.bind_tools(tools)

	system_instruction = (
		"You are the Data Agent for Montreal Mobility.\n"
        "You have two ways to get information:\n"
        "1) Use WEATHER TOOLS for current or historical weather requests.\n"
        "2) Generate a SQL query (SELECT/WITH only) for traffic, 311, or collision data.\n"
        "If you generate SQL, wrap it in ```sql blocks.\n"
        f"Audience: {state.get('audience')}\n"
        f"Context: {state.get('retrieved_context')}"
	)

	response = llm_with_tools.invoke([SystemMessage(content=system_instruction)] + messages)

	if getattr(response, "tool_calls", None):
		return {"generated_query": None, "messages": [response]}
	
	raw_text = response.content

	try:
		parsed_sql = _strip_llm_wrappers(raw_text)

		if not parsed_sql:
			return {"generated_query": None, "messages": [response]}
		
		safe_sql = _sanitize_sql_query(parsed_sql)
		return {
			"generated_query": safe_sql,
			"messages": [response], 
			"query_error": None
			}
	
	except ValueError as ve:
		error_message = str(ve)
		return {
			"generated_query": None,
			"messages": [response],
			"query_error": f"Unsafe or invalid SQL generated: {error_message}"
		}