import re
try:
    from langchain_core.tools import tool
except Exception:  # pragma: no cover - fallback for lightweight test stubs
    def tool(*_args, **_kwargs):
        def _decorator(func):
            return func

        return _decorator

from pydantic import BaseModel, Field

_SQL_BLOCK_PATTERN = re.compile(r"```(?:sql)?\s*(.*?)```", re.IGNORECASE | re.DOTALL)
_XML_TAG_PATTERN = re.compile(r"<\/?(?:sql|query|answer|response)[^>]*>", re.IGNORECASE)
_LINE_COMMENT_PATTERN = re.compile(r"--.*?$", re.MULTILINE)
_BLOCK_COMMENT_PATTERN = re.compile(r"/\*.*?\*/", re.DOTALL)

_FORBIDDEN_SQL_KEYWORDS = {
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE", 
    "ATTACH", "DETACH", "PRAGMA", "VACUUM", "CREATE", "REPLACE", 
    "GRANT", "REVOKE", "COMMIT", "ROLLBACK", "BEGIN", 
    "EXEC", "EXECUTE", "CALL"
}

def _strip_llm_wrappers(raw_text: str) -> str:
    text = (raw_text or "").strip()
    if not text: return ""
    fenced_match = _SQL_BLOCK_PATTERN.search(text)
    if fenced_match: return fenced_match.group(1).strip()
    text = _XML_TAG_PATTERN.sub("", text).strip()
    if text.lower().startswith("sql:"): return text[4:].strip()
    return text

def _normalize_sql(sql: str) -> str:
    sql = _BLOCK_COMMENT_PATTERN.sub(" ", sql)
    sql = _LINE_COMMENT_PATTERN.sub(" ", sql)
    sql = re.sub(r"\s+", " ", sql).strip()
    if sql.endswith(";"): sql = sql[:-1].strip()
    return sql

def _sanitize_sql_query(candidate: str) -> str:
    if not candidate: raise ValueError("Empty SQL query generated by LLM.")
    sql = _normalize_sql(candidate)
    if not sql: raise ValueError("SQL query is empty after normalization.")
    if ";" in sql: raise ValueError("Only one SQL statement is allowed.")
    
    upper_sql = sql.upper()
    if not (upper_sql.startswith("SELECT ") or upper_sql.startswith("WITH ")):
        raise ValueError("Only read-only SQL queries (SELECT/WITH) are allowed.")
    for keyword in _FORBIDDEN_SQL_KEYWORDS:
        if re.search(rf"\b{re.escape(keyword)}\b", upper_sql):
            raise ValueError(f"Forbidden SQL keyword detected: {keyword}")
    return sql

class SQLInput(BaseModel):
    query: str = Field(description="La requête SQL (SELECT/WITH) à valider et exécuter.")

@tool("generate_and_validate_sql", args_schema=SQLInput)
def sql_generator_tool(query: str) -> str:
    """
    Outil OBLIGATOIRE pour interroger la base de données sur les collisions, 311, etc.
    Valide et prépare une requête SQL.
    """
    if not query:
        return "SQL_ERROR: Requête SQL vide ou non fournie."
    
    try:
        parsed_sql = _strip_llm_wrappers(query)
        if not parsed_sql:
            parsed_sql = query
            
        safe_sql = _sanitize_sql_query(parsed_sql)
        
        return f"VALID_SQL_READY_TO_EXECUTE: {safe_sql}"
        
    except ValueError as ve:
        return f"SQL_ERROR: Unsafe or invalid SQL generated: {str(ve)}"