networks:
  mobilitycopilot_net:
    external: true
    name: mobilitycopilot_net

services:
  nginx:
    image: nginx:alpine
    container_name: mobility_nginx
    networks:
      - mobilitycopilot_net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped